// Demo Data Array
export const projects = [
  {
    id: 1,
    title: "Horinathpur SESDP High School, Bera, Pabna.",
    date: "March 4, 2021",
    category: "EED",
    img: "/one.png",
  },
  {
    id: 2,
    title: "Maintenance Work, Pabna Sadar",
    date: "March 4, 2021",
    category: "LGED",
    img: "/two.jpg",
  },
  {
    id: 3,
    title: "Fire Protection System",
    date: "March 4, 2021",
    category: "NHA",
    img: "/three.png",
  },
  {
    id: 4,
    title: "Power Grid Company of Bangladesh",
    date: "March 4, 2021",
    category: "PGCB",
    img: "/four.jpg",
  },
  {
    id: 5,
    title: "Public Work Department, Khulna",
    date: "March 4, 2021",
    category: "PWD",
    img: "/pwd.jpg",
  },
  {
    id: 6,
    title: "Public Work Department, Kushtia",
    date: "March 4, 2021",
    category: "PWD",
    img: "/pwd-1.jpg",
  },
  {
    id: 7,
    title: "Public Work Department, Natore",
    date: "March 4, 2021",
    category: "PWD",
    img: "/pwd-2.jpg",
  },
  {
    id: 8,
    title: "Lalmonirhat Public Work Department",
    date: "March 4, 2021",
    category: "PWD",
    img: "/pwd-3.jpg",
  },
  {
    id: 9,
    title: "Public Work Department, Dhaka",
    date: "March 4, 2021",
    category: "PWD",
    img: "/pwd-4.jpg",
  },
  {
    id: 10,
    title: "Complete Various Work Of Power Grid Company Ltd.",
    date: "March 4, 2021",
    category: "PGCB",
    img: "/PGCB.jpg",
  },
  {
    id: 11,
    title: "Public Work Department, Pabna",
    date: "March 4, 2021",
    category: "PWD",
    img: "/pwd-5.jpg",
  },
  {
    id: 12,
    title: "National Housing Authority Others Related Work",
    date: "March 4, 2021",
    category: "NHA",
    img: "/NHA.jpg",
  },
  {
    id: 13,
    title: "Nizamuddin Azgar Ali College, Santhia, Pabna",
    date: "March 4, 2021",
    category: "EED",
    img: "/EED.jpg",
  },
  {
    id: 14,
    title: "Solar Systems Work",
    date: "March 4, 2021",
    category: "NHA",
    img: "/NHA-1.jpg",
  },
  {
    id: 15,
    title: "Electric Sub-Station Equipment & Diesel Generator",
    date: "March 4, 2021",
    category: "NHA",
    img: "/NHA-2.png",
  },
  {
    id: 16,
    title: "Primary Education Development Project, Pabna",
    date: "March 4, 2021",
    category: "LGED",
    img: "/LGED-1.jpg",
  },
  {
    id: 17,
    title: "Bagatipara Womens Degree College, Natore",
    date: "March 4, 2021",
    category: "EED",
    img: "/EED-1.jpg",
  },
  {
    id: 18,
    title: "Chalanbil Womens College, Singra, Natore",
    date: "March 4, 2021",
    category: "EED",
    img: "/EED-2.jpg",
  },
  {
    id: 19,
    title: "Miapur Dakhil Madrasha, Santhia Upazilla",
    date: "March 4, 2021",
    category: "EED",
    img: "/EED-3.jpg",
  },
  {
    id: 20,
    title: "Jonail M. L High School, Boraigram, Natore",
    date: "March 4, 2021",
    category: "EED",
    img: "/EED-4.png",
  },
  {
    id: 21,
    title: "Pabna Edward College",
    date: "March 4, 2021",
    category: "EED",
    img: "/EED-5.jpg",
  },
  {
    id: 22,
    title: "Salimpur College, Ishwardi, Pabna",
    date: "March 4, 2021",
    category: "EED",
    img: "/EED-6.jpg",
  },
  {
    id: 23,
    title: "Santhia Degree College, Pabna",
    date: "March 4, 2021",
    category: "EED",
    img: "/EED-7.png",
  },
  {
    id: 24,
    title: "Maukhara Womens Degree College, Natore",
    date: "March 4, 2021",
    category: "EED",
    img: "/EED-8.jpg",
  },
  {
    id: 25,
    title: "Jamuna Oil Company Limited",
    date: "March 4, 2021",
    category: "BPC",
    img: "/BPC-1.jpg",
  },
  {
    id: 26,
    title: "Lalmonirhat Public Work Department",
    date: "March 4, 2021",
    category: "BPC",
    img: "/BPC.jpg",
  },
];

export const categories = ["All Projects", "BPC", "EED", "LGED", "NHA", "PGCB", "PWD"];