import Navbar from '@/component/Navbar/Navbar';
import './globals.css';
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="w-full mx-auto">
        <Navbar></Navbar>
        {children}
      </body>
    </html>
  );
}
