import Navbar from '@/components/Navbar';
import './globals.css';
import Footer from '@/components/Footer';

export const metadata = {
  title: 'Sazin Construction Ltd',
  description: 'Generated by create next app',
  icons: {
    icon: '/FavIcon.png',       // default favicon
    shortcut: '/FavIcon.png',   // for browser shortcut
    apple: '/FavIcon.png',      // for iOS devices
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="w-full mx-auto">
        <Navbar />
        {children}
        <Footer/>
      </body>
    </html>
  );
}