import Navbar from '@/components/Navbar';
import './globals.css';
import Footer from '@/components/Footer';
import ScrollToTop from '../utils/ScrollToTop';
import { Montserrat } from 'next/font/google';
import Providers from '../utils/QueryProviders';

const montserrat = Montserrat({
  subsets: ['latin'],
  display: 'swap',
});

export const metadata = {
  title: 'Sazin Construction Ltd',
  description: 'Generated by create next app',
  icons: {
    icon: '/FavIcon.png',       // default favicon
    shortcut: '/FavIcon.png',   // for browser shortcut
    apple: '/FavIcon.png',      // for iOS devices
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${montserrat.className} bg-black dark:bg-gray-800`}>

{/* className="w-full mx-auto max-w-[100rem] relative" */} 
      <body> 
        <Providers>
        <ScrollToTop />
        <Navbar/>
        {children}
        <Footer/>
        </Providers>
      </body>
    </html>
  );
}