export const productsData=[
    {
      "image": "https://images.unsplash.com/photo-1591115765373-520fd36a14e6?q=80&w=800",
      "title": "Vortex Half-Face Helmet",
      "subTitle": "Urban Style",
      "description": "A modern half-face helmet with a unique design.",
      "price": 89.99,
      "category": "Half-Face",
      "rating": 4.8,
      "stock": 20,
    },
    {
      "image": "https://images.unsplash.com/photo-1591115765373-520fd36a14e6?q=80&w=800",
      "title": "Trailblazer Open-Face Helmet",
      "subTitle": "Urban Style",
      "description": "A modern open-face helmet with a unique design.",
      "price": 75.50,
      "category": "Open-Face",
      "rating": 4.7,
      "stock": 15,
    },
    {
      "image": "https://images.unsplash.com/photo-1591115765373-520fd36a14e6?q=80&w=800",
      "title": "Guardian Modular Helmet",
      "subTitle": "Urban Style",
      "description": "A modern modular helmet with a unique design.",
      "price": 159.99,
      "category": "Modular-Face",
      "rating": 4.9,
      "stock": 25,
    },
    {
      "image": "https://images.unsplash.com/photo-1591115765373-520fd36a14e6?q=80&w=800",
      "title": "CyberX Full-Face Helmet",
      "subTitle": "Urban Style",
      "description": "A modern full-face helmet with a unique design.",
      "price": 199.99,
      "category": "Full-Face",
      "rating": 4.8,
      "stock": 20,
    },
    {
      "image": "https://images.unsplash.com/photo-1591115765373-520fd36a14e6?q=80&w=800",
      "title": "Urban Rider Half-Face",
      "subTitle": "Urban Style",
      "description": "A modern half-face helmet with a unique design.",
      "price": 65.00,
      "category": "Half-Face",
      "rating": 4.6,
      "stock": 10,
    },
    {
      "image": "https://images.unsplash.com/photo-1591115765373-520fd36a14e6?q=80&w=800",
      "title": "Classic Cruiser Open-Face",
      "subTitle": "Urban Style",
      "description": "A modern open-face helmet with a unique design.",
      "price": 82.95,
      "category": "Open-Face",
      "rating": 4.5,
      "stock": 12,
    },
    {
      "image": "https://images.unsplash.com/photo-1591115765373-520fd36a14e6?q=80&w=800",
      "title": "Voyager Modular Pro",
      "subTitle": "Urban Style",
      "description": "A modern modular helmet with a unique design.",
      "price": 175.50,
      "category": "Modular-Face",
      "rating": 4.7,
      "stock": 18,
    },
    {
      "image": "https://images.unsplash.com/photo-1591115765373-520fd36a14e6?q=80&w=800",
      "title": "Xtreme Full-Face Shield",
      "subTitle": "Urban Style",
      "description": "A modern full-face helmet with a unique design.",
      "price": 225.00,
      "category": "Full-Face",
      "rating": 4.9,
      "stock": 30,
    },
    {
      "image": "https://images.unsplash.com/photo-1591115765373-520fd36a14e6?q=80&w=800",
      "title": "Sprint Half-Face Lite",
      "subTitle": "Urban Style",
      "description": "A modern half-face helmet with a unique design.",
      "price": 59.99,
      "category": "Half-Face",
      "rating": 4.6,
      "stock": 10,
    },
    {
      "image": "https://images.unsplash.com/photo-1591115765373-520fd36a14e6?q=80&w=800",
      "title": "Breeze Open-Face Air",
      "subTitle": "Urban Style",
      "description": "A modern open-face helmet with a unique design.",
      "price": 70.25,
      "category": "Open-Face",
      "rating": 4.7,
      "stock": 10,
    },
    {
      "image": "https://images.unsplash.com/photo-1591115765373-520fd36a14e6?q=80&w=800",
      "title": "Transform Modular GT",
      "subTitle": "Urban Style",
      "description": "A modern modular helmet with a unique design.",
      "price": 189.95,
      "category": "Modular-Face",
      "rating": 4.9,
      "stock": 25,
    },
    {
      "image": "https://images.unsplash.com/photo-1591115765373-520fd36a14e6?q=80&w=800",
      "title": "Titan Full-Face Carbon",
      "subTitle": "Urban Style",
      "description": "A modern full-face helmet with a unique design.",
      "price": 249.99,
      "category": "Full-Face",
      "rating": 4.9,
      "stock": 25,
    },
    {
      "image": "https://images.unsplash.com/photo-1591115765373-520fd36a14e6?q=80&w=800",
      "title": "Street Hawk Half-Face",
      "subTitle": "Urban Style",
      "description": "A modern half-face helmet with a unique design.",
      "price": 79.99,
      "category": "Half-Face",
      "rating": 4.6,
      "stock": 10,
    },
    {
      "image": "https://images.unsplash.com/photo-1591115765373-520fd36a14e6?q=80&w=800",
      "title": "Retro Open-Face Classic",
      "subTitle": "Classic Retro Style",
      "description": "A timeless classic with a modern twist.",
      "price": 89.95,
      "category": "Open-Face",
      "rating": 4.7,
      "stock": 15,
    },
    {
      "image": "https://images.unsplash.com/photo-1591115765373-520fd36a14e6?q=80&w=800",
      "title": "Evolution Modular X",
      "subTitle": "Urban Style",
      "description": "A modern modular helmet with a unique design.",
      "price": 165.00,
      "category": "Modular-Face",
      "rating": 4.9,
      "stock": 25,
    }
  ]