export const projects = [
  { id: 1, category: "Civil", title: "Ruppur Nuclear Power Plant", sub_title: "Construction of Vertical extension from 5th floor to9th floor Rajshahi Krishi Unnayan BankRAKUB Headquarter includes RCC work, Brickwork, Internal sanitary, Internal electrification,Lift installation, Air cooler, Pump motor etc.(ReTender)", date: "2025-01-10", img: "/project1.png" },
  { id: 2, category: "Electro", title: "Metro Rail Power System", sub_title: "Construction of Vertical extension from 5th floor to9th floor Rajshahi Krishi Unnayan BankRAKUB Headquarter includes RCC work, Brickwork, Internal sanitary, Internal electrification,Lift installation, Air cooler, Pump motor etc.(ReTender)", date: "2025-02-05", img: "/project2.png" },
  { id: 3, category: "Agro", title: "Agro Cold Storage Facility", sub_title: "Construction of Vertical extension from 5th floor to9th floor Rajshahi Krishi Unnayan BankRAKUB Headquarter includes RCC work, Brickwork, Internal sanitary, Internal electrification,Lift installation, Air cooler, Pump motor etc.(ReTender)", date: "2025-03-15", img: "/project3.png" },
  { id: 4, category: "Safety", title: "Fire & Safety Training Center", sub_title: "Construction of Vertical extension from 5th floor to9th floor Rajshahi Krishi Unnayan BankRAKUB Headquarter includes RCC work, Brickwork, Internal sanitary, Internal electrification,Lift installation, Air cooler, Pump motor etc.(ReTender)", date: "2025-04-20", img: "/project4.png" },
  { id: 5, category: "Civil", title: "Dhaka Elevated Expressway", sub_title: "Construction of Vertical extension from 5th floor to9th floor Rajshahi Krishi Unnayan BankRAKUB Headquarter includes RCC work, Brickwork, Internal sanitary, Internal electrification,Lift installation, Air cooler, Pump motor etc.(ReTender)", date: "2025-05-01", img: "/civil2.jpg" },
  { id: 6, category: "Electro", title: "Hospital Electrical Works", sub_title: "Construction of Vertical extension from 5th floor to9th floor Rajshahi Krishi Unnayan BankRAKUB Headquarter includes RCC work, Brickwork, Internal sanitary, Internal electrification,Lift installation, Air cooler, Pump motor etc.(ReTender)", date: "2025-05-18", img: "/electro2.jpg" },
  { id: 7, category: "Agro", title: "Fisheries Expansion Project", sub_title: "Construction of Vertical extension from 5th floor to9th floor Rajshahi Krishi Unnayan BankRAKUB Headquarter includes RCC work, Brickwork, Internal sanitary, Internal electrification,Lift installation, Air cooler, Pump motor etc.(ReTender)", date: "2025-06-10", img: "/agro2.jpg" },
  { id: 8, category: "Safety", title: "Helmet & Safety Accessories Plant", sub_title: "Construction of Vertical extension from 5th floor to9th floor Rajshahi Krishi Unnayan BankRAKUB Headquarter includes RCC work, Brickwork, Internal sanitary, Internal electrification,Lift installation, Air cooler, Pump motor etc.(ReTender)", date: "2025-07-01", img: "/safety2.jpg" },
  { id: 9, category: "Safety", title: "Surveillance & Security Upgrade", sub_title: "Construction of Vertical extension from 5th floor to9th floor Rajshahi Krishi Unnayan BankRAKUB Headquarter includes RCC work, Brickwork, Internal sanitary, Internal electrification,Lift installation, Air cooler, Pump motor etc.(ReTender)", date: "2025-07-15", img: "/safety2.jpg" },
  { id: 10, category: "Civil", title: "Bridge Construction", sub_title: "Construction of Vertical extension from 5th floor to9th floor Rajshahi Krishi Unnayan BankRAKUB Headquarter includes RCC work, Brickwork, Internal sanitary, Internal electrification,Lift installation, Air cooler, Pump motor etc.(ReTender)", date: "2025-08-01", img: "/civil3.jpg" },
  { id: 11, category: "Electro", title: "Airport Electrical Upgrade", sub_title: "Construction of Vertical extension from 5th floor to9th floor Rajshahi Krishi Unnayan BankRAKUB Headquarter includes RCC work, Brickwork, Internal sanitary, Internal electrification,Lift installation, Air cooler, Pump motor etc.(ReTender)", date: "2025-08-10", img: "/electro3.jpg" },
  { id: 12, category: "Agro", title: "Organic Farming Project", sub_title: "Construction of Vertical extension from 5th floor to9th floor Rajshahi Krishi Unnayan BankRAKUB Headquarter includes RCC work, Brickwork, Internal sanitary, Internal electrification,Lift installation, Air cooler, Pump motor etc.(ReTender)", date: "2025-08-15", img: "/agro1.jpg" },
];
